### ISSUE TITLE
Ei toimi Iceweaselissa?

### ISSUE THREAD

**Issue by jluttine** [tuomassalo/vr-no-flash#1]
Hei! Kiitos tästä, olen piiiiitkään kaivannut jotakin flash-vapaata tapaa valita istumapaikat junasta. :smiley:

En kuitenkaan saanut tätä toimimaan. Ajoin build.sh -skriptin ja ymmärtääkseni se lopulta suoriutui onnistuneesti (loi `dist/coaches` kansioon kuvia ja javascriptiä).

Mitään ei kuitenkaan tapahdu kun valitsen bookmarkin VR:n sivulla. "Valitse Paikat" nappiin ei ilmesty sydäntä ja sitä painaessa se edelleen herjaa flashin puutteesta. En oikein osaa debugata tätä, kun javascript yms ei ole kovin tuttua, joten jos osaat vinkata, miten saan jotain hyödyllistä tietoa esiin niin voisin koittaa sitä saada. Käytän Iceweaselia (suunnilleen Firefox) versio 43.0.4.

**Comment by jluttine** [comment]
Sain hieman debugattua: bookmarkin javascript-koodiin tuli välilyöntien paikalle `%20`, ne piti itse vaihtaa välilyönneiksi varmaankin. Mutta silti ei tapahdu mitään edelleenkään.

**Comment by tuomassalo** [comment]
Hei! Laiskuroin ohjeiden kanssa, enkä maininnut että lopputulos täytyy hostata jossain HTTPS-palvelimella. Täydensin ohjeita.

Hostailuun ei ole tarvetta, ellei halua muokata koodia. Git-versiota hostataan täällä: https://venko.net/naapuri/vr/

**Comment by jluttine** [comment]
Ah, ok, kiitos, nyt toimii!
