### ISSUE TITLE
Joustavan luokan vaunut 1 ja 7 eivät näy Helsinki - Tampere pendolinossa

### ISSUE THREAD

**Issue by tepel** [tuomassalo/vr-no-flash#6]
Helsinki-Tampere pendolinon joustavan luokan paikanvalinta ei toimi. Vaunut 1 ja 7 ovat tyhjiä. Testasin chrome liitännäistä. Jos tuo toimisi niin ottaisin tämän heti käyttöön.

**Comment by tuomassalo** [comment]
Kummallinen bugi, jonka taustoja en ehdi nyt tutkia. Tekemäni korjauksen pitäisi kuitenkin auttaa.

Huom: @artoliukkonen - päivitä 51.fi:een uusi versio nf.min.js:stä (tai koko dist), niin vika korjaantuu Chrome-liitännäiseenkin.
