### ISSUE TITLE
vr.aarre.net nurin

### ISSUE THREAD

**Issue by mpartel** [tuomassalo/vr-no-flash#7]
vr.aarre.net osoittaa CNAMElla venko.net:iin, jolle nimipalvelin ei tällä hetkellä anna IP-osoitetta

**Comment by tuomassalo** [comment]
Hmm, en onnistunut toistamaan ongelmaa eilen enkä nyt. Toistuuko ongelma sulla yhä?

```$ host vr.aarre.net. 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

vr.aarre.net is an alias for venko.net.
venko.net has address 212.246.29.148
venko.net mail is handled by 10 mail.venko.net.

**Comment by mpartel** [comment]
Kas, kun käynnistin reitittimeni `dnsmasq`:n uudestaan, tuo `venko.net has address 212.246.29.148` -rivi ilmestyi ja sivu toimii taas. Miksiköhän se oli cachettanut puuttuvan, ja vielä noin pitkäksi aikaa :confused: 

Reitittimeni käyttää 1.1.1.1 ja 1.0.0.1.
